import Head from "next/head";
import { useState, useEffect } from "react";
import { Header } from "./components/header/header";
import { Main } from "./components/main/main";
import getFormattedWeatherData from "@/service/weather-app";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export default function Home() {
  const [query, setQuery] = useState({ q: "tashkent" });
  const [units, setUnits] = useState("metric");
  const [weather, setWeather] = useState("");
  const [background, setBackground] = useState("blur");

  useEffect(() => {
    const fetchWeather = async () => {
      await getFormattedWeatherData({ ...query, units })
        .then((data) => {
          toast.success(
            `Successfully fetched weather fot ${data.name}, ${data.country}.`
          );
          setWeather(data);
        })
        .catch((error) => {
          toast.error("Error country not found.");
        });
    };
    fetchWeather();
  }, [query, units]);

  const formatBackground = () => {
    if (!weather) return "from-cyan-700 to-blue-700";

    const threshold = units === "metric" ? 20 : 60;
    if (weather.temp <= threshold) return "from-cyan-700 to-blue-700";

    return "from-yellow-700 to-orange-700";
  };

  useEffect(() => {
    const backgroundFunc = () => {
      if (weather.details === "Smoke" || weather.details === "Mist") {
        setBackground("smoke");
      } else if (weather.details === "Rain" || weather.details === "Drizzle") {
        setBackground("rain");
      } else if (weather.details === "Snow") {
        setBackground("snow");
      } else if (weather.details === "Clouds" || weather.details === "Clear") {
        setBackground("clouds");
      } else {
        setBackground("default");
      }
    };
    backgroundFunc();
    console.log("Hello:)");
  }, [setBackground, weather]);

  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={`App bg-gradient-to-br ${formatBackground()} mx-auto max-w-screen-md py-5 px-24 h-fit z-30 mt-10 mb-10 pb-24`}
      >
        <div className={background}></div>
        <header>
          <Header
            weather={weather}
            setQuery={setQuery}
            units={units}
            setUnits={setUnits}
          />
        </header>

        <main>
          <Main weather={weather} />
        </main>
        <ToastContainer autoClose={5000} theme="colored" newestOnTop={true} />
      </div>
    </>
  );
}
